<template>
    <div class="ui grid">
        <div  class="column one wide">
            <div class="album">
                <div class="ui two column grid ">
                    <div class="column dblue">
                       
                    </div>
                    <div class="column dblue">
                        
                    </div>
                </div>
            </div>
        </div>
     </div>
</template>

<script>
    export default {
        
    }
</script>

<style scoped>

.album {

   /* width:100%;
   height:90px; */
   padding:5px;
   /* background: #4d4b4b;  */
   color:white;
   font-size:12px;
}

.cover {
    float:left;
}
.cover img {
    width:80px;
}
.trackinfo {
    float: left;
    width: 50%;
    padding: 10px 10px;
}

.dblue {
    background-color: #3c6382!important;
    color: #fff;
}
</style>